"""empty message

Revision ID: 069766380029
Revises: 07936f7a215a
Create Date: 2017-10-30 06:13:40.150918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069766380029'
down_revision = '07936f7a215a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ansible_config', sa.Column('switch_pass', sa.String(length=40), nullable=True))
    op.add_column('ansible_config', sa.Column('switch_user', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ansible_config', 'switch_user')
    op.drop_column('ansible_config', 'switch_pass')
    # ### end Alembic commands ###
